
APPNAME := Pretendo	

ASM    := nasm
CPP    := clang
LD     := clang
RM     := rm -f
RES	   := xres
STRIP  := strip

DEFINES  := 
INCLUDES := -Ilibines2/lib/include/ -Isrc/ -Isrc/haiku/ \
		 	-I/boot/system/develop/headers/x86 \
		 	-I/boot/system/develop/headers/x86/libxml2

ASMFLAGS := -f elf
CPPFLAGS := -O3 $(INCLUDES) -W -Wall -Wno-implicit-fallthrough -std=c++17 #-flto
LDFLAGS  := -L/boot/common/lib \
			-lbe -lroot -ltranslation -ltracker -lgame -lmedia -lxml2 -lz -lstdc++ #-flto

ASM_FILES := \
	src/asm/blitters_x86.asm \
	src/asm/copies_x86.asm

CPP_FILES := \
	libines2/lib/Header.cpp	\
	libines2/lib/Rom.cpp	\
	\
	src/Apu.cpp \
	src/Bus.cpp \
	src/Cart.cpp \
	src/Controller.cpp \
	src/Cpu.cpp \
	src/Dmc.cpp \
	src/Envelope.cpp \
	src/Input.cpp \
	src/LengthCounter.cpp \
	src/LinearCounter.cpp \
	src/Mapper.cpp \
	src/MemoryMappedFile.cpp \
	src/Nes.cpp \
	src/Noise.cpp \
	src/Palette.cpp \
	src/Ppu.cpp \
	src/SaveState.cpp \
	src/Timer.cpp \
	src/Triangle.cpp \
	\
	src/mappers/Bandai.cpp \
	src/mappers/MMC3.cpp \
	src/mappers/VRC2.cpp \
	src/mappers/VRC4.cpp \
	src/mappers/VRC6.cpp \
	src/mappers/Mapper000.cpp \
	src/mappers/Mapper001.cpp \
	src/mappers/Mapper002.cpp \
	src/mappers/Mapper003.cpp \
	src/mappers/Mapper004.cpp \
	src/mappers/Mapper005.cpp \
	src/mappers/Mapper007.cpp \
	src/mappers/Mapper009.cpp \
	src/mappers/Mapper010.cpp \
	src/mappers/Mapper011.cpp \
	src/mappers/Mapper013.cpp \
	src/mappers/Mapper015.cpp \
	src/mappers/Mapper016.cpp \
	src/mappers/Mapper018.cpp \
	src/mappers/Mapper019.cpp \
	src/mappers/Mapper021.cpp \
	src/mappers/Mapper022.cpp \
	src/mappers/Mapper023.cpp \
	src/mappers/Mapper024.cpp \
	src/mappers/Mapper025.cpp \
	src/mappers/Mapper026.cpp \
	src/mappers/Mapper027.cpp \
	src/mappers/Mapper032.cpp \
	src/mappers/Mapper033.cpp \
	src/mappers/Mapper034.cpp \
	src/mappers/Mapper040.cpp \
	src/mappers/Mapper043.cpp \
	src/mappers/Mapper046.cpp \
	src/mappers/Mapper048.cpp \
	src/mappers/Mapper050.cpp \
	src/mappers/Mapper057.cpp \
	src/mappers/Mapper058.cpp \
	src/mappers/Mapper061.cpp \
	src/mappers/Mapper064.cpp \
	src/mappers/Mapper066.cpp \
	src/mappers/Mapper068.cpp \
	src/mappers/Mapper069.cpp \
	src/mappers/Mapper071.cpp \
	src/mappers/Mapper075.cpp \
	src/mappers/Mapper076.cpp \
	src/mappers/Mapper079.cpp \
	src/mappers/Mapper086.cpp \
	src/mappers/Mapper088.cpp \
	src/mappers/Mapper090.cpp \
	src/mappers/Mapper113.cpp \
	src/mappers/Mapper118.cpp \
	src/mappers/Mapper144.cpp \
	src/mappers/Mapper159.cpp \
	src/mappers/Mapper163.cpp \
	src/mappers/Mapper180.cpp \
	src/mappers/Mapper201.cpp \
	src/mappers/Mapper206.cpp \
	src/mappers/Mapper218.cpp \
	src/mappers/Mapper226.cpp \
	src/mappers/Mapper228.cpp \
	src/mappers/Mapper231.cpp \
	src/mappers/Mapper232.cpp \
	src/mappers/Mapper240.cpp \
	src/mappers/Mapper241.cpp \
	src/mappers/Mapper242.cpp \
	src/mappers/Mapper243.cpp \
	src/mappers/Mapper245.cpp \
	\
	src/haiku/AboutWindow.cpp \
	src/haiku/AudioStream.cpp \
	src/haiku/HaikuMain.cpp \
	src/haiku/InputView.cpp \
	src/haiku/InputWindow.cpp \
	src/haiku/LinkView.cpp \
	src/haiku/MenuBarIcon.cpp \
	src/haiku/Mutex.cpp \
	src/haiku/NameTableView.cpp\
	src/haiku/NameTableWindow.cpp \
	src/haiku/PaletteView.cpp \
	src/haiku/PaletteWindow.cpp \
	src/haiku/PatternTableView.cpp \
	src/haiku/PatternTableWindow.cpp \
	src/haiku/PretendoApp.cpp \
	src/haiku/PretendoView.cpp \
	src/haiku/PretendoWindow.cpp \
	src/haiku/ROMFilePanel.cpp \
	src/haiku/ROMInfoView.cpp \
	src/haiku/ROMInfoWindow.cpp \
	src/haiku/Settings.cpp \
	src/haiku/Splitters.cpp \
	src/haiku/VideoScreen.cpp
	
SOURCES 	:= $(CPP_FILES) $(ASM_FILES)
RESOURCES 	:= src/haiku/pretendo.rsrc
OBJECTS 	:= $(CPP_FILES:.cpp=.o) $(ASM_FILES:.asm=.o)
                
.SUFFIXES: .cpp .h .asm .o

.cpp.o:
	@echo compiling $<...
	@$(CPP) $(CPPFLAGS) $(DEFINES) -c $< -o $@ 1>/dev/null
		
.asm.o:
	@echo assembling $<...
	@$(ASM) $(ASMFLAGS) $(DEFINES) $< -o $@ 1>/dev/null


$(APPNAME): $(OBJECTS)
	@echo linking $@...
	@$(LD) $(LDFLAGS) $(OBJECTS) -o $@ 1>/dev/null
	@echo stripping $@...
	@$(STRIP) $@
	@echo adding resources to $@...
	@$(RES) -o $@ $(RESOURCES)
	@echo done.


.PHONY: clean 
clean:
	@echo cleaning...
	@$(RM) $(OBJECTS) $(APPNAME)
	@echo done.
	

